version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE=mongodb+srv://dhruv:EoK2DAoebizpcYW2@cluster0.ezsavro.mongodb.net/parking-solns?retryWrites=true&w=majority
      - DATABASE_PASSWORD=EoK2DAoebizpcYW2
      - JWT_SECRET=this-really-is-a-secret-for-sure
      - JWT_EXPIRES_IN=90d
      - JWT_COOKIE_EXPIRES_IN=90
      - EMAIL_HOST=sandbox.smtp.mailtrap.io
      - EMAIL_USERNAME=4aba44003a9487
      - EMAIL_PASSWORD=6d08c137e6f320
      - EMAIL_PORT=587
      - EMAIL_FROM=22bma011@nith.ac.in
      - GMAIL_USERNAME=22bma011@nith.ac.in
      - GMAIL_PASSWORD=bupvtwsxqoxyqfky
      # STRIPE_SECRET_KEY will be set via Railway environment variables
    volumes:
      - uploads:/app/public/img
    restart: unless-stopped
    networks:
      - parkkar-network

volumes:
  uploads:

networks:
  parkkar-network:
    driver: bridge
